# Meta data
name:         base-ui
authors:      Andrew Castro
description:  html css components.

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://base-ui.io
